#!/bin/bash
# Installation of FMCA binder

export PREFIX="$(python -c 'import sys; print(sys.prefix)')"


cd /tmp && \
git clone https://github.com/pybind/pybind11.git  && \
     cd pybind11 && \
     python3 setup.py build && \
     python3 setup.py install --prefix=/usr  \
		--install-headers=/usr/include/pybind11 --skip-build && \
     mv build/lib/pybind11 /usr/local/lib  && \
     cp -r /usr/local/lib/pybind11/share/cmake  /usr/lib && \
     git clone https://gitlab.com/libeigen/eigen.git && \
     cd eigen && \
     mkdir build && cd build && \
     cmake -D CMAKE_INSTALL_PREFIX=${CONDA_PREFIX} -D CMAKE_C_COMPILER=$CC -D CMAKE_CXX_COMPILER=$CXX -D CMAKE_INSTALL_LIBDIR=${CONDA_PREFIX}/lib .. && \
     make && make install && \
cd /home
